### PR TITLE
Increase of Node Lookup Retry & Exclude Canonical Node Types

### PR DESCRIPTION
**Pull request by shaswot77**
# Description

- Increase max retries for looking up nodes as for larger environment the import can take some time
- Exclude Canonical Node Types

# Checklist:
- [x] Added a label: `bug-fix`, `feature`, or `enhancement`
- [x] PR description written

### CODE REVIEW

**Review by wigsaparelli — APPROVED** [review]
Remind me why we're looking up graph nodes (what's the Terraform functionality we're providing)?

**Comment by P2P-Nathan** [comment]
> Remind me why we're looking up graph nodes (what's the Terraform functionality we're providing)?

In the case of the Account Dashboards I've been using this functionality to look up the graph node which a tile will target.  For example the SalesForce nodes of each Customer Account gets looked up and passed into the template to be used in the Scope settings.

It is probably possible to use a Gremlin Scoped tile and skip the lookup of the nodeId, but this wouldn't match the UI's behaviour and might look odd when someone goes to perform an edit.

```
 "scope": {
          "bindings": {
            "ids_ncTbNH15BGQ1r6sHKne9": [
              "{{monitoring_plugin_node_id}}"
            ]
          },
          "query": "g.V().has('id', within(ids_ncTbNH15BGQ1r6sHKne9))",
          "queryDetail": {
            "ids": [
              "{{monitoring_plugin_node_id}}"
            ]
          }
        },
```

**Review by P2P-Nathan — APPROVED** [review]
This looks good, one thought came to mind after replying to @wigsaparelli on how I had been using the Node lookup.

Should we have a property on the lookup to allow a `null` to be returned when the lookup fails?  

In the case of the Account Dashboards (and maybe others) I could see cases where you would perform something to the effect of "If there is a SalesForce node, add this tile, if not, just skip it"

A big however though, I don't know if this is good Terraform practice or not.

**Comment by shaswot77** [comment]
> Remind me why we're looking up graph nodes (what's the Terraform functionality we're providing)?

This was initially added so we can support fixed scoped dashboards. I have created an example usage here - https://registry.terraform.io/providers/squaredup/squaredup/latest/docs/resources/dashboard

**Comment by shaswot77** [comment]
> This looks good, one thought came to mind after replying to @wigsaparelli on how I had been using the Node lookup.
> 
> Should we have a property on the lookup to allow a `null` to be returned when the lookup fails?
> 
> In the case of the Account Dashboards (and maybe others) I could see cases where you would perform something to the effect of "If there is a SalesForce node, add this tile, if not, just skip it"
> 
> A big however though, I don't know if this is good Terraform practice or not.

Sounds reasonable, I have added that.

**Review by P2P-Nathan — APPROVED** [review]
Updated changes look good

**Pull request merged**
